### ISSUE TITLE
problem: run into signal:killed 

### ISSUE THREAD

**Issue by shaibearary** [Stackerstan/mindmachine#22]
```
2023-01-16 14:07:11 INFO => OP_RETURN: d094026cb717aebe795acf53af78fc11cf45bd565e2af86c2a05a4a3a21885f0
2023-01-16 14:07:11 INFO => Initialising the eventpacker at 765554
2023-01-16 14:07:23 INFO => OP_RETURN: c0485bc1204ad10546d85bcfadd66ccbaa03bff9b364ed44ee20a1e8d299be80
2023-01-16 14:07:23 INFO => Initialising the eventpacker at 765555
signal: killed
make: *** [Makefile:39: reset] Error 1
```

**Comment by shaibearary** [comment]
ping @stanstacks

**Comment by pqingshuang** [comment]
also sometimes it return 
```

2023-01-16 14:33:05 INFO => fetching optional relays from nostr-watch
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x793165]

goroutine 1 [running]:
mindmachine/mindmachine.getOptionalRelays()
        /home/qspang/stackerstan/mindmachine/mindmachine/initConfig.go:71 +0x85
mindmachine/mindmachine.InitConfig(0xc0000f6180)
        /home/qspang/stackerstan/mindmachine/mindmachine/initConfig.go:43 +0x3df
main.main()
        /home/qspang/stackerstan/mindmachine/cmd/mindmachine/main.go:52 +0x1ff
exit status 2
make: *** [Makefile:39: reset] Error 1
```

**Comment by shaibearary** [comment]
I cannot figure it out because Im dumb, 
 
It is a OOM kill but i dont know how to fix haha
```
qspang@LAPTOP-E94QJJKL:~$ dmesg | egrep -i -B100 'killed process'
.......
[83298.704937] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/,task=cliListener,pid=15293,uid=1000
[83298.706684] Out of memory: Killed process 15293 (cliListener) total-vm:10709916kB, anon-rss:7527468kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:18028kB oom_score_adj:0

```

**Comment by stanstacks** [comment]
@pqingshuang have you seen this again recently?

**Comment by shaibearary** [comment]
@stanstacks No, I will close this problem now ~:)
