### ISSUE TITLE
problem: invalid memory address

### ISSUE THREAD

**Issue by shaibearary** [Stackerstan/mindmachine#23]
```
2023-01-17 12:09:03 INFO => fetching optional relays from nostr-watch
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x793165]

goroutine 1 [running]:
mindmachine/mindmachine.getOptionalRelays()
        /home/qspang/stackerstan/mindmachine/mindmachine/initConfig.go:71 +0x85
mindmachine/mindmachine.InitConfig(0xc0000f6180)
        /home/qspang/stackerstan/mindmachine/mindmachine/initConfig.go:43 +0x3df
main.main()
        /home/qspang/stackerstan/mindmachine/cmd/mindmachine/main.go:52 +0x1ff
exit status 2
make: *** [Makefile:39: reset] Error 1
```

solution: 
https://github.com/Stackerstan/mindmachine/blob/36026be5dfee539afaebbf03ad9ca9d08c99de2f/mindmachine/initConfig.go#L71

defer shoud be decleared only  if err == nil

**Comment by pqingshuang** [comment]
relaed to another error in #22

**Comment by stanstacks** [comment]
@pqingshuang FYI if you are the one who posts and issue and then you (or anyone else) solves it (and it's really solved) you can just close it.

**Comment by shaibearary** [comment]
OKK
